(ns shrine.model.product
  (:require [malli.core :as malli]))

(def valid?
  "Validates a product map."
  (malli/validator
   [:map
    [:category [:enum :accessories :clothing :home]]
    [:id :int]
    [:featured? :boolean]
    [:name :string]
    [:price :int]]))

(defn asset-name
  [product]
  (str (:id product) "-0.jpg"))

(defn asset-package
  [_product]
  "shrine-images")

(defn to-string
  [product]
  (str (:name product) " (id=" (:id product) ")"))
