(ns shrine.main
  (:require ["package:flutter/material.dart" :as m]
            ["dart:core" :as dart]
            [shrine.home :as home]
            [shrine.login :as login]
            [cljd.flutter :as f]))

(defonce app-state (atom {}))

(defn main []
  (f/run
   (m/MaterialApp
    .title "Shrine"
    .initialRoute "/login"
    .routes {"/login" login/login-page
             "/" home/home-page})))
